# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Publications"
  url = "#publications"
  weight = 20

[[main]]
  name = "Working Papers"
  url = "#workingpapers"
  weight = 30

[[main]]
  name = "Media and Talks"
  url = "#mediaandtalks"
  weight = 40
  
[[main]]  
  name = "CV"
  url = "static/cv.pdf"
  weight = 50

